name: xanbot

build-tools: nodejs

executable:
  main: Main.hs
  dependencies:
    - base
    - reflex-basic-host
    - http-types
    - stm
    - websockets
    - mtl
    - reflex
  source-dirs: [src]
