name: xanbot

ghc-options: -Wall

executable:
  main: Main.hs
  dependencies:
    - lens
    - base
    - text
    - containers
    - http-types
    - stm
    - mtl
    - websockets
    - network
    - file-embed
    - time
    - async
    - reflex
    - aeson
    - data-msgpack
    - reflex-basic-host
    - ansi-wl-pprint
    - template-haskell
    - jwt
  source-dirs: [src]
  ghc-options: -threaded -rtsopts -with-rtsopts=-N
