name: xanbot

ghc-options: -Wall

executable:
  main: Main.hs
  dependencies:
    - base
    # - lens
    - text
    # - containers
    # - http-types
    # - stm
    # - mtl
    # - websockets
    # - network
    # - file-embed
    # - time
    # - async
    # - cookie
    # - reflex
    # - reflex-dom
    # - aeson
    # - reflex-basic-host
    # - ansi-wl-pprint
    # - template-haskell
    # - jwt
  source-dirs: [src]
  ghc-options: -threaded -rtsopts -with-rtsopts=-N
