// flow-typed signature: 04f318b271cb29aeabe59aea8c7bbad5
// flow-typed version: <<STUB>>/react-foundation_v0.9.6/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-foundation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-foundation' {
  import type { Component, Node } from 'react';

  declare export var Menu: Class<
    Component<{|
      className?: string,
      isDropdown?: boolean,
      isVertical?: boolean,
      iconsOnTop?: boolean,
      children?: Node,
    |}>
  >;

  declare export var MenuItem: Class<
    Component<{| isActive?: boolean, children?: Node |}>
  >;

  declare export var MenuText: Class<Component<{| children?: Node |}>>;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-foundation/lib/components/accordion' {
  declare module.exports: any;
}

declare module 'react-foundation/lib/components/badge' {
  declare module.exports: any;
}

declare module 'react-foundation/lib/components/breadcrumbs' {
  declare module.exports: any;
}

declare module 'react-foundation/lib/components/button-group' {
  declare module.exports: any;
}

declare module 'react-foundation/lib/components/button' {
  declare module.exports: any;
}

declare module 'react-foundation/lib/components/callout' {
  declare module.exports: any;
}

declare module 'react-foundation/lib/components/close-button' {
  declare module.exports: any;
}

declare module 'react-foundation/lib/components/element' {
  declare module.exports: any;
}

declare module 'react-foundation/lib/components/flex-video' {
  declare module.exports: any;
}

declare module 'react-foundation/lib/components/grid' {
  declare module.exports: any;
}

declare module 'react-foundation/lib/components/icon' {
  declare module.exports: any;
}

declare module 'react-foundation/lib/components/label' {
  declare module.exports: any;
}

declare module 'react-foundation/lib/components/media-object' {
  declare module.exports: any;
}

declare module 'react-foundation/lib/components/menu' {
  declare module.exports: any;
}

declare module 'react-foundation/lib/components/pagination' {
  declare module.exports: any;
}

declare module 'react-foundation/lib/components/progress-bar' {
  declare module.exports: any;
}

declare module 'react-foundation/lib/components/responsive' {
  declare module.exports: any;
}

declare module 'react-foundation/lib/components/reveal' {
  declare module.exports: any;
}

declare module 'react-foundation/lib/components/slider' {
  declare module.exports: any;
}

declare module 'react-foundation/lib/components/switch' {
  declare module.exports: any;
}

declare module 'react-foundation/lib/components/tabs' {
  declare module.exports: any;
}

declare module 'react-foundation/lib/components/thumbnail' {
  declare module.exports: any;
}

declare module 'react-foundation/lib/components/top-bar' {
  declare module.exports: any;
}

declare module 'react-foundation/lib/components/xy-grid' {
  declare module.exports: any;
}

declare module 'react-foundation/lib/enums' {
  declare module.exports: any;
}

declare module 'react-foundation/lib/index' {
  declare module.exports: any;
}

declare module 'react-foundation/lib/utils' {
  declare module.exports: any;
}

declare module 'react-foundation/src/components/accordion' {
  declare module.exports: any;
}

declare module 'react-foundation/src/components/badge' {
  declare module.exports: any;
}

declare module 'react-foundation/src/components/breadcrumbs' {
  declare module.exports: any;
}

declare module 'react-foundation/src/components/button-group' {
  declare module.exports: any;
}

declare module 'react-foundation/src/components/button' {
  declare module.exports: any;
}

declare module 'react-foundation/src/components/callout' {
  declare module.exports: any;
}

declare module 'react-foundation/src/components/close-button' {
  declare module.exports: any;
}

declare module 'react-foundation/src/components/element' {
  declare module.exports: any;
}

declare module 'react-foundation/src/components/flex-video' {
  declare module.exports: any;
}

declare module 'react-foundation/src/components/grid' {
  declare module.exports: any;
}

declare module 'react-foundation/src/components/icon' {
  declare module.exports: any;
}

declare module 'react-foundation/src/components/label' {
  declare module.exports: any;
}

declare module 'react-foundation/src/components/media-object' {
  declare module.exports: any;
}

declare module 'react-foundation/src/components/menu' {
  declare module.exports: any;
}

declare module 'react-foundation/src/components/pagination' {
  declare module.exports: any;
}

declare module 'react-foundation/src/components/progress-bar' {
  declare module.exports: any;
}

declare module 'react-foundation/src/components/responsive' {
  declare module.exports: any;
}

declare module 'react-foundation/src/components/reveal' {
  declare module.exports: any;
}

declare module 'react-foundation/src/components/slider' {
  declare module.exports: any;
}

declare module 'react-foundation/src/components/switch' {
  declare module.exports: any;
}

declare module 'react-foundation/src/components/tabs' {
  declare module.exports: any;
}

declare module 'react-foundation/src/components/thumbnail' {
  declare module.exports: any;
}

declare module 'react-foundation/src/components/top-bar' {
  declare module.exports: any;
}

declare module 'react-foundation/src/components/xy-grid' {
  declare module.exports: any;
}

declare module 'react-foundation/src/enums' {
  declare module.exports: any;
}

declare module 'react-foundation/src/index' {
  declare module.exports: any;
}

declare module 'react-foundation/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-foundation/lib/components/accordion.js' {
  declare module.exports: $Exports<'react-foundation/lib/components/accordion'>;
}
declare module 'react-foundation/lib/components/badge.js' {
  declare module.exports: $Exports<'react-foundation/lib/components/badge'>;
}
declare module 'react-foundation/lib/components/breadcrumbs.js' {
  declare module.exports: $Exports<
    'react-foundation/lib/components/breadcrumbs'
  >;
}
declare module 'react-foundation/lib/components/button-group.js' {
  declare module.exports: $Exports<
    'react-foundation/lib/components/button-group'
  >;
}
declare module 'react-foundation/lib/components/button.js' {
  declare module.exports: $Exports<'react-foundation/lib/components/button'>;
}
declare module 'react-foundation/lib/components/callout.js' {
  declare module.exports: $Exports<'react-foundation/lib/components/callout'>;
}
declare module 'react-foundation/lib/components/close-button.js' {
  declare module.exports: $Exports<
    'react-foundation/lib/components/close-button'
  >;
}
declare module 'react-foundation/lib/components/element.js' {
  declare module.exports: $Exports<'react-foundation/lib/components/element'>;
}
declare module 'react-foundation/lib/components/flex-video.js' {
  declare module.exports: $Exports<
    'react-foundation/lib/components/flex-video'
  >;
}
declare module 'react-foundation/lib/components/grid.js' {
  declare module.exports: $Exports<'react-foundation/lib/components/grid'>;
}
declare module 'react-foundation/lib/components/icon.js' {
  declare module.exports: $Exports<'react-foundation/lib/components/icon'>;
}
declare module 'react-foundation/lib/components/label.js' {
  declare module.exports: $Exports<'react-foundation/lib/components/label'>;
}
declare module 'react-foundation/lib/components/media-object.js' {
  declare module.exports: $Exports<
    'react-foundation/lib/components/media-object'
  >;
}
declare module 'react-foundation/lib/components/menu.js' {
  declare module.exports: $Exports<'react-foundation/lib/components/menu'>;
}
declare module 'react-foundation/lib/components/pagination.js' {
  declare module.exports: $Exports<
    'react-foundation/lib/components/pagination'
  >;
}
declare module 'react-foundation/lib/components/progress-bar.js' {
  declare module.exports: $Exports<
    'react-foundation/lib/components/progress-bar'
  >;
}
declare module 'react-foundation/lib/components/responsive.js' {
  declare module.exports: $Exports<
    'react-foundation/lib/components/responsive'
  >;
}
declare module 'react-foundation/lib/components/reveal.js' {
  declare module.exports: $Exports<'react-foundation/lib/components/reveal'>;
}
declare module 'react-foundation/lib/components/slider.js' {
  declare module.exports: $Exports<'react-foundation/lib/components/slider'>;
}
declare module 'react-foundation/lib/components/switch.js' {
  declare module.exports: $Exports<'react-foundation/lib/components/switch'>;
}
declare module 'react-foundation/lib/components/tabs.js' {
  declare module.exports: $Exports<'react-foundation/lib/components/tabs'>;
}
declare module 'react-foundation/lib/components/thumbnail.js' {
  declare module.exports: $Exports<'react-foundation/lib/components/thumbnail'>;
}
declare module 'react-foundation/lib/components/top-bar.js' {
  declare module.exports: $Exports<'react-foundation/lib/components/top-bar'>;
}
declare module 'react-foundation/lib/components/xy-grid.js' {
  declare module.exports: $Exports<'react-foundation/lib/components/xy-grid'>;
}
declare module 'react-foundation/lib/enums.js' {
  declare module.exports: $Exports<'react-foundation/lib/enums'>;
}
declare module 'react-foundation/lib/index.js' {
  declare module.exports: $Exports<'react-foundation/lib/index'>;
}
declare module 'react-foundation/lib/utils.js' {
  declare module.exports: $Exports<'react-foundation/lib/utils'>;
}
declare module 'react-foundation/src/components/accordion.js' {
  declare module.exports: $Exports<'react-foundation/src/components/accordion'>;
}
declare module 'react-foundation/src/components/badge.js' {
  declare module.exports: $Exports<'react-foundation/src/components/badge'>;
}
declare module 'react-foundation/src/components/breadcrumbs.js' {
  declare module.exports: $Exports<
    'react-foundation/src/components/breadcrumbs'
  >;
}
declare module 'react-foundation/src/components/button-group.js' {
  declare module.exports: $Exports<
    'react-foundation/src/components/button-group'
  >;
}
declare module 'react-foundation/src/components/button.js' {
  declare module.exports: $Exports<'react-foundation/src/components/button'>;
}
declare module 'react-foundation/src/components/callout.js' {
  declare module.exports: $Exports<'react-foundation/src/components/callout'>;
}
declare module 'react-foundation/src/components/close-button.js' {
  declare module.exports: $Exports<
    'react-foundation/src/components/close-button'
  >;
}
declare module 'react-foundation/src/components/element.js' {
  declare module.exports: $Exports<'react-foundation/src/components/element'>;
}
declare module 'react-foundation/src/components/flex-video.js' {
  declare module.exports: $Exports<
    'react-foundation/src/components/flex-video'
  >;
}
declare module 'react-foundation/src/components/grid.js' {
  declare module.exports: $Exports<'react-foundation/src/components/grid'>;
}
declare module 'react-foundation/src/components/icon.js' {
  declare module.exports: $Exports<'react-foundation/src/components/icon'>;
}
declare module 'react-foundation/src/components/label.js' {
  declare module.exports: $Exports<'react-foundation/src/components/label'>;
}
declare module 'react-foundation/src/components/media-object.js' {
  declare module.exports: $Exports<
    'react-foundation/src/components/media-object'
  >;
}
declare module 'react-foundation/src/components/menu.js' {
  declare module.exports: $Exports<'react-foundation/src/components/menu'>;
}
declare module 'react-foundation/src/components/pagination.js' {
  declare module.exports: $Exports<
    'react-foundation/src/components/pagination'
  >;
}
declare module 'react-foundation/src/components/progress-bar.js' {
  declare module.exports: $Exports<
    'react-foundation/src/components/progress-bar'
  >;
}
declare module 'react-foundation/src/components/responsive.js' {
  declare module.exports: $Exports<
    'react-foundation/src/components/responsive'
  >;
}
declare module 'react-foundation/src/components/reveal.js' {
  declare module.exports: $Exports<'react-foundation/src/components/reveal'>;
}
declare module 'react-foundation/src/components/slider.js' {
  declare module.exports: $Exports<'react-foundation/src/components/slider'>;
}
declare module 'react-foundation/src/components/switch.js' {
  declare module.exports: $Exports<'react-foundation/src/components/switch'>;
}
declare module 'react-foundation/src/components/tabs.js' {
  declare module.exports: $Exports<'react-foundation/src/components/tabs'>;
}
declare module 'react-foundation/src/components/thumbnail.js' {
  declare module.exports: $Exports<'react-foundation/src/components/thumbnail'>;
}
declare module 'react-foundation/src/components/top-bar.js' {
  declare module.exports: $Exports<'react-foundation/src/components/top-bar'>;
}
declare module 'react-foundation/src/components/xy-grid.js' {
  declare module.exports: $Exports<'react-foundation/src/components/xy-grid'>;
}
declare module 'react-foundation/src/enums.js' {
  declare module.exports: $Exports<'react-foundation/src/enums'>;
}
declare module 'react-foundation/src/index.js' {
  declare module.exports: $Exports<'react-foundation/src/index'>;
}
declare module 'react-foundation/src/utils.js' {
  declare module.exports: $Exports<'react-foundation/src/utils'>;
}
